describe('Greenkart Market', () => {

    it('Places an order for Brocolli', () => {
        cy.visit('https://rahulshettyacademy.com/seleniumPractise/#/')
        cy.get('input[type=search]').type('Brocolli')
        cy.get('.products')
            .find('.product')
            .contains('Brocolli')
            .should('be.visible')
        cy.get('.product:contains(Brocolli)')
            .find('.quantity')
            .should('have.value', '1')
        cy.get('.product:contains(Brocolli)')
            .find('.increment')
            .dblclick()
        cy.get('.product:contains(Brocolli)')
            .find('.quantity')
            .should('have.value', '3')
        cy.get('.product:contains(Brocolli)')
            .find('button').contains('ADD TO CART')
            .click()
            .should('contain.text', 'ADDED')
            .and('be.visible')
        cy.get('.cart-icon').click()
        cy.get('.cart-preview.active')
            .find('.cart-item')
            .contains('Brocolli')
            .should('be.visible')
        cy.get('.cart-preview.active button').click()
        cy.get('.cartTable')
            .find('.product-name')
            .contains('Brocolli')
            .should('be.visible')
        cy.get('.promoCode').type('test')
        cy.get('.promoBtn').click()
        cy.wait(3000)
        cy.get('.promoInfo')
            .contains('Invalid code ..!')
            .should('be.visible')
        cy.get('button').contains('Place Order').click()
        cy.get('.products').find('select').select('Armenia')
        cy.wait(500)
        cy.get('.chkAgree').check()
        cy.get('button').contains('Proceed').click()
        cy.get('.wrapperTwo span').contains('Thank you').should('be.visible')
    })
})